### ISSUE TITLE
Si esto es una historia de usuario, tiene que incluir beneficio para el cliente

### ISSUE THREAD

**Issue by JJ** [JaimeGM96/IV-JGM#10]
Si no, como explicamos en clase, son simplemente usuarios. Corrige #4 y también el texto que aquí esta escrito, de forma que pueda ayudar a dirigir el PR actual

https://github.com/JaimeGM96/IV-JGM/blob/2d91d6ba1796038e0514cb2b58fbe154bc0fed76/docs/historias-usuario.md?plain=1#L10

**Comment by JaimeGM96** [comment]
Actualizada la descripción. Considero que queda más claro el beneficio que obtiene el Cliente.
