### ISSUE TITLE
:negative_squared_cross_mark: Variables de tipo readonly

### ISSUE THREAD

**Issue by MauronMP** [JaimeGM96/IV-JGM#11]
Buenas @JaimeGM96, en vista de lo que ha explicado JJ en la clase de teoría, me ha parecido conveniente cambiar ciertas variables a tipo readonly, este tipo de dato lo puedes ver [en este enlace](https://www.typescripttutorial.net/typescript-tutorial/typescript-readonly/). Básicamente este tipo de dato hace al objeto inmutable, se asigna una vez y no se puede modificar más, por ejemplo en el caso de la clase Usuario he puesto a los datos que no se cambiarán más.

Si te parece correcto lo dejo así, si no, cambio a la versión anterior.

**Comment by JaimeGM96** [comment]
Hola @MauronMP, perdón por tardar tanto en contestar. He estado mirando los cambios que comentas y me parece buena idea, dejalo así 👍🏼

**Comment by MauronMP** [comment]
:sunglasses:👍🏼
