### ISSUE TITLE
:eyes: [M0] Como programador, necesito saber con qué lenguaje quieres trabajar

### ISSUE THREAD

**Issue by MauronMP** [JaimeGM96/IV-JGM#13]
Elección de lenguaje

_Originally posted by @MauronMP in https://github.com/JaimeGM96/IV-JGM/issues/3#issuecomment-1293344027_

**Comment by MauronMP** [comment]
Buenas @JaimeGM96, esto lo habiamos hablado ya en otros issues que se cerrarán cuando se fusione, de igual modo el lenguaje a utilizar será Typescript como habíamos dicho

**Comment by MauronMP** [comment]
> En cuanto al lenguaje de programación, he pensado que TypeScript puede ser una buena opción ya que es un lenguaje muy versátil, se puede usar tanto en el backend como en el frontend, es un lenguaje que añade tipado a JavaScript, tiene una sintaxis sencilla parecida a la de C++, lenguaje que conocemos de los primeros años de carrera, etc. Básicamente Typescript funciona sobre todo lo que está hecho en JavaScript y además de eso, añade nuevas funcionalidades.
> 
> Por otro lado, las clases, como se detallan en los milestones y en las historias de usuario, serán nutricionista y cliente. La implementación está en tu mano inicialmente y después seguiremos comentando si hay que modificar algo.
> 
> _Originally posted by @JaimeGM96 in [#5 (comment)](https://github.com/JaimeGM96/IV-JGM/issues/5#issuecomment-1271395460)_

**Comment by JJ** [comment]
La elección del lenguaje no forma parte de ninguna historia de usuario.

**Comment by MauronMP** [comment]
Es cierto, no se puede quitar la referencia del issue #13 a la HU #3, pero entonces no será parte del HU #3
