### ISSUE TITLE
:eyes: [M0] Qué es una dieta y qué es una comida

### ISSUE THREAD

**Issue by MauronMP** [JaimeGM96/IV-JGM#18]
Partiendo de la historia de usuario 1 #3.
Necesito saber qué es una dieta, yo había creado ya una clase Dietas y una clase Comida, pero no sé realmente que se entiende por una dieta y por una comida, aun con los cambios que he hecho yo, necesito saber qué entiendes por dieta y comida.

**Comment by JaimeGM96** [comment]
Una comida es un desayuno, almuerzo, cena, etc. Lo ideal de cada comida es que sea equilibrada y para ello tiene que tener proteinas, hidratos de carbono y grasas, cada uno en su medida.

**Comment by MauronMP** [comment]
De acuerdo, se ajusta entonces a los parámetros que tengo creados.

**Comment by JaimeGM96** [comment]
En una Dieta se indica la cantidad de comida que hay que consumir para cada comida. Para eso tenemos que saber la cantidad de calorias totales que hay que consumir y eso dividirlo entre el número de comidas.

**Comment by MauronMP** [comment]
Okey, respecto a las dietas, pondré entonces las calorías totales

**Comment by MauronMP** [comment]
#3

**Comment by MauronMP** [comment]
He incluido una variable llamada totalCalorias en la clase Dieta

**Comment by JJ** [comment]
Sigue sin estar asignado a una HU. No sé de qué HU estamos hablando ni cómo aporta valor al cliente.

**Comment by MauronMP** [comment]
Pero si en [la HU1](https://github.com/JaimeGM96/IV-JGM/issues/3), está mencionado al igual que los otros issues, ¿no estaría bien?

![image](https://user-images.githubusercontent.com/43990474/198335516-bf4e28a7-89d3-44c0-aa6d-6d8fe281aae8.png)


Y en la HU1 salen referenciados:
![image](https://user-images.githubusercontent.com/43990474/198335794-9918c7d4-015d-415a-98aa-0e590b0c83ef.png)

**Comment by JJ** [comment]
Tienes que mencionarlo *en el cuerpo del issue* no en un comentario, que además va de la HU al issue, no al revés.
