### ISSUE TITLE
:negative_squared_cross_mark: Como programador necesito saber varios datos para desarrollar el [HU1]

### ISSUE THREAD

**Issue by MauronMP** [JaimeGM96/IV-JGM#5]
Teniendo en cuenta lo que se indica en el [milestone 0](https://github.com/JaimeGM96/IV-JGM/milestone/1), necesito conocer los siguientes puntos:

- Qué lenguaje se quiere utilizar en caso de tener alguno ya pensado.
- Qué tipo de datos tienes que usar, qué estructura tienes pensada y qué tipo de datos se tienen que tener en cuenta con las dietas.
- Si tienen algún tipo de restricciones.

En cualquier caso, puedo aportar sugerencias a cada punto mencionado, pero ya decides lo que te conviene más.

**Comment by JaimeGM96** [comment]
En cuanto al lenguaje de programación, he pensado que TypeScript puede ser una buena opción ya que es un lenguaje muy versátil, se puede usar tanto en el backend como en el frontend, es un lenguaje que añade tipado a JavaScript, tiene una sintaxis sencilla parecida a la de C++, lenguaje que conocemos de los primeros años de carrera, etc. Básicamente Typescript funciona sobre todo lo que está hecho en JavaScript y además de eso, añade nuevas funcionalidades.

Por otro lado, las clases, como se detallan en los milestones y en las historias de usuario, serán nutricionista y cliente. La implementación está en tu mano inicialmente y después seguiremos comentando si hay que modificar algo.

**Comment by MauronMP** [comment]
Buenas @JaimeGM96, por lo que he estado viendo, necesitas entonces que haga: 

- Una clase cliente con sus datos personales y datos de su cuerpo (altura, peso, etc.).
- Una clase Nutricionista con sus datos profesionales.
- Y con las dietas no sé si necesitas una clase y si la necesitaras, ¿qué tendría que tener como datos?

**Comment by JaimeGM96** [comment]
Esas clases son correctas, más adelante puede que haga falta una más. En cuanto a las dietas, es necesario crear una clase para definirlas. Los atributos podrían ser:
- Calorías
- Número de comidas
- Id nutricionista
- Id cliente

**Comment by MauronMP** [comment]
Buenas @JaimeGM96, he estado mirando TypeScript, tengo una duda con lo que me has dicho de las clases, ¿necesitas constructores y funciones getter o setter de cada propiedad, de alguna en específico o solo con sus propiedades?

**Comment by JaimeGM96** [comment]
Constructor y getters de todos los atributos.

**Comment by JJ** [comment]
El lenguaje y las estructuras de datos deben usar diferentes issues. Y este issue debería referenciarse cuando se hagan cambios en el código.

**Comment by JJ** [comment]
> Constructor y getters de todos los atributos.

¿Por qué? ¿Quién ha pedido eso?

**Comment by JJ** [comment]
> Esas clases son correctas, más adelante puede que haga falta una más. En cuanto a las dietas, es necesario crear una clase para definirlas. Los atributos podrían ser:
> 
> * Calorías
> * Número de comidas
> * Id nutricionista
> * Id cliente

¿Por qué podrían ser? ¿Qué HU dice eso?

**Comment by JJ** [comment]
Los issues deben referirse a una historia de usuario, y siempre plantear problemas. Por favor, hacedlo así.

**Comment by JaimeGM96** [comment]
> ¿Por qué? ¿Quién ha pedido eso?

En el documento del objetivo 2 hay una sección que indica que hay que tener en cuenta que el lenguaje elegido tenga mutabilidad y por lo tanto permita el uso de getters, creí que era buena idea además de una buena práctica implementar los getters.

**Comment by JJ** [comment]
> > ¿Por qué? ¿Quién ha pedido eso?
> 
> En el documento del objetivo 2 hay una sección que indica que hay que tener en cuenta que el lenguaje elegido tenga mutabilidad y por lo tanto permita el uso de getters, creí que era buena idea además de una buena práctica implementar los getters.

Que lo permita el lenguaje no quiere decir que haya que implementarlo en cada uno de los objetos.

**Comment by MauronMP** [comment]
> > > ¿Por qué? ¿Quién ha pedido eso?
> > 
> > 
> > En el documento del objetivo 2 hay una sección que indica que hay que tener en cuenta que el lenguaje elegido tenga mutabilidad y por lo tanto permita el uso de getters, creí que era buena idea además de una buena práctica implementar los getters.
> 
> Que lo permita el lenguaje no quiere decir que haya que implementarlo en cada uno de los objetos.

Entonces, ¿debería de quitar todos o dejar por ejemplo los getter de los Id's?

**Comment by JJ** [comment]
> > > > ¿Por qué? ¿Quién ha pedido eso?
> > > 
> > > 
> > > En el documento del objetivo 2 hay una sección que indica que hay que tener en cuenta que el lenguaje elegido tenga mutabilidad y por lo tanto permita el uso de getters, creí que era buena idea además de una buena práctica implementar los getters.
> > 
> > 
> > Que lo permita el lenguaje no quiere decir que haya que implementarlo en cada uno de los objetos.
> 
> Entonces, ¿debería de quitar todos o dejar por ejemplo los getter de los Id's?

Debes de crear un issue donde, usando domain-driven design, se vaya analizando el dominio del problema y decidiendo qué entidades y objetos valor se van a usar y como se relacionan entre si.
