### ISSUE TITLE
:negative_squared_cross_mark: Elección de las clases y atributos

### ISSUE THREAD

**Issue by MauronMP** [JaimeGM96/IV-JGM#8]
Buenas @JaimeGM96, por lo que he estado viendo, necesitas entonces que haga: 

- Una clase cliente con sus datos personales y datos de su cuerpo (altura, peso, etc.).
- Una clase Nutricionista con sus datos profesionales.
- Y con las dietas no sé si necesitas una clase y si la necesitaras, ¿qué tendría que tener como datos?

_Originally posted by @MauronMP in https://github.com/JaimeGM96/IV-JGM/issues/5#issuecomment-1273099883_

**Comment by MauronMP** [comment]
Esas clases son correctas, más adelante puede que haga falta una más. En cuanto a las dietas, es necesario crear una clase para definirlas. Los atributos podrían ser:
- Calorías
- Número de comidas
- Id nutricionista
- Id cliente

_Originally posted by @JaimeGM96 in https://github.com/JaimeGM96/IV-JGM/issues/5#issuecomment-1273640545_

**Comment by JaimeGM96** [comment]
Habiendo tenido una reunión con un nutricionista y después de haber comentado los datos que necesita y que refleja en una dieta, se pueden realizar diversos cambios en la clase Dieta:
- Tipo de dieta: ya habiamos definido que según el objetivo de peso del cliente (ganar, mantener o perder) teniamos 3 tipos de dietas, hiper-calórica, normo-calórica, hipo-calórica.
- Hidratos de carbono: nº de hidratos que consume en cada comida.
- Proteínas: nº de proteinas que consume en cada comida.
- Grasas: nº de grasas que consume en cada comida.

Como estos atributos son comunes y contienen datos diferentes a cada comida, esta podría ser una nueva clase y que las Dietas contengan tantas Comidas como indica su atributo.

**Comment by MauronMP** [comment]
Buenas, según he entendido, hago una clase llamada 'Comida' con los atributos de:
- Hidratos de carbono
- Proteínas
- Grasas

Y luego en la clase Dietas, un atributo que contenga tantas comidas como indique y una variable que indique el tipo de dieta que es.

**Comment by MauronMP** [comment]
Buenas @JaimeGM96, he creado: 

- Una clase llamada tipoDietas con las tres que me has dicho, es de tipo enum.
- Una clase Comida con los tres atributos mencionados.
- En la clase Dietas le paso por parámetro en el constructor un array de la clase Comida con 'x' comidas y de igual modo saco el número total de comidas y sus datos en el fichero de Prueba.ts.
- He cambiado algunas variables a público y he dejado otras en privado.
