### ISSUE TITLE
:negative_squared_cross_mark: Constructores, funciones getter y setter

### ISSUE THREAD

**Issue by MauronMP** [JaimeGM96/IV-JGM#9]
Buenas @JaimeGM96, he estado mirando TypeScript, tengo una duda con lo que me has dicho de las clases, ¿necesitas constructores y funciones getter o setter de cada propiedad, de alguna en específico o solo con sus propiedades?

_Originally posted by @MauronMP in https://github.com/JaimeGM96/IV-JGM/issues/5#issuecomment-1274968438_

**Comment by MauronMP** [comment]
> Constructor y getters de todos los atributos.

¿Por qué? ¿Quién ha pedido eso?

_Originally posted by @JJ in https://github.com/JaimeGM96/IV-JGM/issues/5#issuecomment-1284956456_

**Comment by MauronMP** [comment]
Teniendo en cuenta lo que mencionó JJ en el anterior issue, en lugar de crear para todos los atributos un getter, ¿cuál crees que son realmente necesarios?

De igual modo, todas las variables que he creado, son de tipo private, ¿ves necesario cambiar alguna variable a otro tipo?

**Comment by JaimeGM96** [comment]
Los getters que nos podrían interesar serían los datos del cliente y del nutricionista que usaremos posteriormente en la generación de la dieta.

**Comment by JJ** [comment]
> Los getters que nos podrían interesar serían los datos del cliente y del nutricionista que usaremos posteriormente en la generación de la dieta.

Los getters que pueden interesar son los que añaden valor al cliente y están aclarados en un issue relacionado con un HU.
También os rogaría un puntito más de interés en este objetivo. Yo me he comprometido a corregir los objetivos en tres días, creo que tres días para responder a un comentario en un issue o incluso dos es algo más que razonable. Si no, estás impidiendo el avance de tu compañero y el tuyo mismo.

**Comment by MauronMP** [comment]
Teniendo en cuenta eso, nos interesarían datos que son útiles como las medidas de la cintura, cuello y peso, ya que en la generación de las dietas se busca tres objetivos distintos, pero en cada uno, estas medidas son necesarias.

**Comment by MauronMP** [comment]
Buenas, he cambiado algunas variables y las he dejado a públicas y otras si las he dejado en privadas, de igual modo, he hecho más cambios por los otros issues.
